version: "3.8"
services:
    ###
    ### MYSQL - BDD
    ###
    mysql:
        container_name: "openfoodfacts-etl-mysql"
        image: "mysql:latest"
        restart: unless-stopped
        volumes:
            - openfoodfacts-etl-mysql-data:/var/lib/mysql
            - ./docs/database/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - "3306:3306"
        networks:
            - "openfoodfacts-etl-network"

    ###
    ### PHPMYADMIN - VISUALISATION BDD
    ###
    phpmyadmin:
        container_name: "openfoodfacts-etl-phpmyadmin"
        image: "phpmyadmin:latest"
        restart: unless-stopped
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
        ports:
            - "8080:80"
        networks:
            - "openfoodfacts-etl-network"

    ###
    ### CLUSTERING - APACHE SPARK
    ###

#    spark-master:
#        container_name: "openfoodfacts-etl-spark-master"
#        image: "bitnami/spark:latest"
#        restart: unless-stopped
#        ports:
#            - "8081:8080"
#            - "7077:7077"
#        environment:
#            SPARK_MODE: "master"
#            SPARK_MASTER_HOST: "spark-master"
#        networks:
#            - "openfoodfacts-etl-network"
#
#    spark-worker-1:
#        container_name: "openfoodfacts-etl-spark-worker-1"
#        image: "bitnami/spark:latest"
#        restart: unless-stopped
#        ports:
#            - "8082:8080"
#        environment:
#            SPARK_MODE: "worker"
#            SPARK_MASTER_HOST: "spark-master"
#        networks:
#            - "openfoodfacts-etl-network"
#
#    spark-worker-2:
#        container_name: "openfoodfacts-etl-spark-worker-2"
#        image: "bitnami/spark:latest"
#        restart: unless-stopped
#        ports:
#            - "8083:8080"
#        networks:
#            - "openfoodfacts-etl-network"

networks:
    openfoodfacts-etl-network:
        driver: "bridge"
        name: "openfoodfacts-etl-network"

volumes:
    openfoodfacts-etl-mysql-data:
